name: cued_sf2_lab
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - ipympl
  - jupyterlab
  - notebook
  - ipykernel
  - pytest
  - pytest-cov
  - flake8
  - pip:
      - -e .
